# Generated by Django 4.0.4 on 2022-05-19 19:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Utilitys', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('main_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Utilitys.main')),
                ('name', models.CharField(max_length=20)),
                ('price', models.FloatField()),
                ('puyer', models.ManyToManyField(related_name='Puyer', to=settings.AUTH_USER_MODEL)),
                ('seller', models.ManyToManyField(related_name='Seller', to=settings.AUTH_USER_MODEL)),
            ],
            bases=('Utilitys.main',),
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Product.product')),
                ('type', models.CharField(choices=[('S', 'Sigler'), ('P', 'Plorul')], max_length=10)),
                ('count', models.FloatField()),
            ],
            bases=('Product.product',),
        ),
    ]
