# Generated by Django 4.0.4 on 2022-05-19 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Main',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Description',
            fields=[
                ('main_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Utilitys.main')),
                ('desc_ar', models.TextField()),
                ('desc_en', models.TextField()),
            ],
            bases=('Utilitys.main',),
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('main_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Utilitys.main')),
                ('path', models.ImageField(upload_to='', verbose_name='files/images')),
            ],
            bases=('Utilitys.main',),
        ),
    ]
